choose_the_cloud_type_button = "xpath://div[@id='#']"
add_account_next_button = "xpath://button[@data-test-id='add-account-next']"
dot_circle = "css:svg[data-icon='circle-dot']"
copy_script_button = "xpath://button[descendant::span[normalize-space(text())='Copy Script']]"
gcp_onboarding_script_execu_finish_xpath = "xpath://p[text()=' Paste and execute the script into GCP Cloud Shell:']//*[local-name()='svg' and @data-icon='check-circle']"
account_selection_search_input = "xpath://input[@data-test-id='account-selection-search']"
account_selection_tree = "xpath://div[@data-test-id='account-selection-tree']"
account_selection_checkbox_xpath = "xpath://div[contains(@class,'ant-tree-treenode') and descendant::*[text()='#']]//span[@class='ant-tree-checkbox']"
add_account_finish_button = "xpath://button[descendant::span[text()='Finish']]"
business_unit_dropdown = "xpath://div[@class='common-dropdown-wrapper']//span//button"
business_unit_search_box = "xpath://input[@placeholder='Search']"
click_on_business_unit = "xpath://div[@class='dropdown-options-container']//div[1]//label"
integration_id_xpath = "xpath://p[@data-integration-id]"